#+TITLE: Programming |> Multi |> Platfrom |> Paradigm
#+AUTHOR: Piotr Limanowski
#+KEYWORDS: jinterface, integration, jvm, beam, otp, elixir, lfe, clojure

* Level:  Daily User
* Topics: new or emerging languages, new programming paradigms
* Time: 60 min 
* Abstract
Polyglot, multiparadigm environments become the bread and butter of every developer's work. 
With the drive towards microservices and reactive software developers start to look into Erlang/OTP platform more often. 
The platform offers incredible tools we can't directly make use of from within JVM languages or can we?

The talk shows the integration between JVM languages and BEAM's LFE/Elixir. 
The fundamental pattern that will be explored are Erlang/OTP as a base platform/language and a JVM-based data access layer.
We will explore JInterface, a set of Java classes which are used to make communication between JVM languages and Erlang, providing a message-based protocol.
In the end the talk compares the JInterface-based approach to HTTP REST-style communication.

After the talk listeners should be able to understand the basics of JVM-BEAM integration strategies as well as benefits of such an architecture.

